// RazorPay Keys
export const razorPayKeyId = 'rzp_test_IfTLGLQI8zPv3i';
export const razorPayKeySecret = 'ho9umdNUSC6PHZM1r1qQtb30';

// oneSignal App ID
export const ONE_SIGNAL_ID = 'c311cd72-7c1e-4c73-8c99-03f9b16be9ef';

// Check login
export const GETTING_MOVIE_LIST = 'GETTING_MOVIE_LIST';
export const MOVIES_FETCHED = 'MOVIES_FETCHED';
export const ERROR_IN_MOVIE_FETCHING = 'ERROR_IN_MOVIE_FETCHING';

// Check login
export const CHECKING_AUTHENTICATION = 'CHECKING_AUTHENTICATION';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const NOT_LOGGED_IN = 'NOT_LOGGED_IN';
export const LOG_OUT_FROM_APP = 'LOG_OUT_FROM_APP';
export const INITIATE_LOGOUT = 'INITIATE_LOGOUT';

// SignIn
export const SIGNING_IN = 'SIGNING_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const RE_INITIALIZE_LOGIN_REDUCER = 'RE_INITIALIZE_LOGIN_REDUCER';
export const RE_INITIALIZING_LOGIN_REDUCER = 'RE_INITIALIZING_LOGIN_REDUCER';

export const RESEND_SIGNING_IN = 'RESEND_SIGNING_IN';
export const RESEND_SIGN_IN_SUCCESS = 'RESEND_SIGN_IN_SUCCESS';
export const RESEND_SIGN_IN_FAILURE = 'RESEND_SIGN_IN_FAILURE';
export const RESEND_INITIALIZE_LOGIN_REDUCER =
  'RESEND_INITIALIZE_LOGIN_REDUCER';
export const RESEND_INITIALIZING_LOGIN_REDUCER =
  'RESEND_INITIALIZING_LOGIN_REDUCER';

//Otp And Auth
export const LOADING_USER_AUTH = 'LOADING_USER_AUTH';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAILURE = 'USER_AUTH_FAILURE';
export const INITIALIZING_AUTH = 'INITIALIZING_AUTH';
export const INITIALIZED_AUTH = 'INITIALIZED_AUTH';

//Get Reward Categories
export const FETCHING_REWARD_CATEGORIES = 'FETCHING_REWARD_CATEGORIES';
export const FETCHING_REWARD_CATEGORIES_SUCCESS =
  'FETCHING_REWARD_CATEGORIES_SUCCESS';
export const FETCHING_REWARD_CATEGORIES_FAILURE =
  'FETCHING_REWARD_CATEGORIES_FAILURE';

//Activities Listing
export const FETCHING_ACTIVITIES = 'FETCHING_ACTIVITIES';
export const FETCHING_ACTIVITIES_SUCCESS = 'FETCHING_ACTIVITIES_SUCCESS';
export const FETCHING_ACTIVITIES_FAILURE = 'FETCHING_ACTIVITIES_FAILURE';

//Get Reward Listing
export const FETCHING_REWARD_LIST = 'FETCHING_REWARD_LIST';
export const FETCHING_REWARD_LIST_SUCCESS = 'FETCHING_REWARD_LIST_SUCCESS';
export const FETCHING_REWARD_LIST_FAILURE = 'FETCHING_REWARD_LIST_FAILURE';

//Get Reward Listing
export const GETTING_REWARD_REDEMPTIONS = 'GETTING_REWARD_REDEMPTIONS';
export const GOT_REDEMPTION_SUCCESS = 'GOT_REDEMPTION_SUCCESS';
export const GOT_REDEMPTION_FAILURE = 'GOT_REDEMPTION_FAILURE';

// USER Detail
export const FETCHING_USER_DETAIL = 'FETCHING_USER_DETAIL';
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';
export const USER_DETAIL_FAILURE = 'USER_DETAIL_FAILURE';

// Dashboard Detail
export const FETCHING_DASHBOARD = 'FETCHING_DASHBOARD';
export const FETCHING_DASHBOARD_SUCCESS = 'FETCHING_DASHBOARD_SUCCESS';
export const FETCHING_DASHBOARD_FAILURE = 'FETCHING_DASHBOARD_FAILURE';

//ORDERS
export const FETCHING_ORDERS = 'FETCHING_ORDERS';
export const FETCHING_ORDERS_SUCCESS = 'FETCHING_ORDERS_SUCCESS';
export const FETCHING_ORDERS_FAILURE = 'FETCHING_ORDERS_FAILURE';

//USER_DATA
export const INITIALIZE_USER_NAME_AGE_LOCATION_REDUCER =
  'INITIALIZE_USER_NAME_AGE_LOCATION_REDUCER';
export const INITIALIZE_USER_NAME_AGE_LOCATION_REDUCERR =
  'INITIALIZE_USER_NAME_AGE_LOCATION_REDUCERR';
export const UPDATING_USER_DATA = 'UPDATING_USER_DATA';
export const USER_DATA_UPDATED_SUCCESS = 'USER_DATA_UPDATED_SUCCESS';
export const USER_DATA_UPDATED_FAILURE = 'USER_DATA_UPDATED_FAILURE';

// Multiple Questions
export const FETCHING_MULTIPLE_QUESTIONS = 'FETCHING_MULTIPLE_QUESTIONS';
export const FETCHING_MULTIPLE_QUESTIONS_SUCCESS =
  'FETCHING_MULTIPLE_QUESTIONS_SUCCESS';
export const FETCHING_MULTIPLE_QUESTIONS_FAILURE =
  'FETCHING_MULTIPLE_QUESTIONS_FAILURE';

//USER_DATA
export const UPDATING_USER_PROFILE = 'UPDATING_USER';
export const UPDATING_USER_PROFILE_SUCCESS = 'UPDATING_USER_PROFILE_SUCCESS';
export const UPDATING_USER_PROFILE_FAILURE = 'UPDATING_USER_PROFILE_FAILURE';
export const INITIALIZE_PROFILE_REDUCER = 'INITIALIZE_PROFILE_REDUCER';
export const INITIALIZE_PROFILE_REDUCERR = 'INITIALIZE_PROFILE_REDUCERR';

//GETING USER DETAIL
export const GETTING_USER_DETAIL = 'GETTING_USER_DETAIL';
export const GOT_USER_DETAIL_SUCCESSFULLY = 'GOT_USER_DETAIL_SUCCESSFULLY';
export const GETTING_USER_DETAIL_FAILURE = 'GETTING_USER_DETAIL_FAILURE';

// UPDATE USER SETTING
export const INITIALIZE_ADDRESS_REDUCER = 'INITIALIZE_ADDRESS_REDUCER';
export const INITIALIZED_ADDRESS_REDUCER = 'INITIALIZED_ADDRESS_REDUCER';

export const UPDATING_USER_ADDRESS = 'UPDATING_USER_ADDRESS';
export const UPDATING_USER_ADDRESS_SUCCESS = 'UPDATING_USER_ADDRESS_SUCCESS';
export const UPDATING_USER_ADDRESS_FAILURE = 'UPDATING_USER_ADDRESS_FAILURE';

export const UPDATING_USER_NOTIFICATION = 'UPDATING_USER_NOTIFICATION';
export const UPDATING_USER_NOTIFICATION_SUCCESS =
  'UPDATING_USER_NOTIFICATION_SUCCESS';
export const UPDATING_USER_NOTIFICATION_FAILURE =
  'UPDATING_USER_NOTIFICATION_FAILURE';

// EMAIL REDUCER
export const UPDATING_EMAIL = 'UPDATING_EMAIL';
export const UPDATING_EMAIL_SUCCESS = 'UPDATING_EMAIL_SUCCESS';
export const UPDATING_EMAIL_FAILURE = 'UPDATING_EMAIL_FAILURE';
export const INITIALIZE_EMAIL_REDUCER = 'INITIALIZE_EMAIL_REDUCER';
export const INITIALIZED_EMAIL_REDUCER = 'INITIALIZED_EMAIL_REDUCER';

// GENDER REDUCER
export const UPDATING_GENDER = 'UPDATING_GENDER';
export const UPDATING_GENDER_SUCCESS = 'UPDATING_GENDER_SUCCESS';
export const UPDATING_GENDER_FAILURE = 'UPDATING_GENDER_FAILURE';
export const INITIALIZE_GENDER_REDUCER = 'INITIALIZE_GENDER_REDUCER';
export const INITIALIZED_GENDER_REDUCER = 'INITIALIZED_GENDER_REDUCER';

//FETCHING DATA FROM FIREBASE
export const FETCHING_USER_DATA_FROM_FIREBASE =
  'FETCHING_USER_DATA_FROM_FIREBASE';
export const FETCHING_SUCCESS_FROM_FIREBASE = 'FETCHING_SUCCESS_FROM_FIREBASE';
export const FETCHING_FAILURE_FROM_FIREBASE = 'FETCHING_FAILURE_FROM_FIREBASE';
export const FETCHING_FAILURE_FROM_FIREBASE_IN_CATCH =
  'FETCHING_FAILURE_FROM_FIREBASE_IN_CATCH';
export const INITIALIZE_INTELLIGENCE = 'INITIALIZE_INTELLIGENCE';
export const INITIALIZED_INTELLIGENCE = 'INITIALIZED_INTELLIGENCE';

// SAVING QUESTIONS
export const SAVING_QUESTIONS = 'SAVING_QUESTIONS';
export const SAVING_QUESTIONS_SUCCESS = 'SAVING_QUESTIONS_SUCCESS';
export const SAVING_QUESTIONS_FAILURE = 'SAVING_QUESTIONS_FAILURE';
export const INITIALIZED_SAVE_QUESTIONS = 'INITIALIZED_SAVE_QUESTIONS';
export const INITIALIZE_SAVE_QUESTIONS = 'INITIALIZE_SAVE_QUESTIONS';

//UPDATE USER IMAGE
export const UPDATING_USER_IMAGE = 'UPDATING_USER_IMAGE';
export const USER_IMAGE_UPDATED_SUCCESS = 'USER_IMAGE_UPDATED_SUCCESS';
export const USER_IMAGE_UPDATED_FAILURE = 'USER_IMAGE_UPDATED_FAILURE';

// GET CITIES

export const GETTING_CITIES = 'GETTING_CITIES';
export const GOT_CITIES_SUCCESSFULLY = 'GOT_CITIES_SUCCESSFULLY';
export const GOT_CITIES_FAILURE = 'GOT_CITIES_FAILURE';
